name: "Backup Notion Workspace"

on:
  push:
    branches:
      - main
  schedule:
    -   cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run backup script
        run: npm install && npm run backup
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE_ID }}
          NOTION_USER_ID: ${{ secrets.NOTION_USER_ID }}

      - name: Checkout backup repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.REPO_USERNAME }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_PERSONAL_ACCESS_TOKEN }}
          path: "notion-backup"
      
      - name: Commit changes to backup repo
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        run: |
          cp -a backup/. notion-backup/backup/
          cd notion-backup
          git config --local user.email "${GIT_EMAIL}"
          git config --local user.name "${GIT_USERNAME}"
          stats="$(git diff --shortstat | xargs)"
          if [ -z "${stats}" ]; then stats=none; fi
          printf "Updated: %s\n\nUpdates: %s" "$(date)" "$stats" > README.md
          git add backup README.md
          git commit -m "Updates: $stats"
          git push